package com.maspro.masprojavafx;

public enum Tag { // types of vehicles. complete list. C for car, M for motorcycle
    C_MICRO,
    C_SEDAN,
    C_HATCHBACK,
    C_UNIVERSAL,
    C_LIFTBACK,
    C_COUPE,
    C_CABRIOLET,
    C_ROADSTER,
    C_TARGA,
    C_LIMOUSINE,
    C_MUSCLE_CAR,
    C_SPORT_CAR,
    C_SUPER_CAR,
    C_SUV,
    C_CROSSOVER,
    C_PICKUP,
    C_VAN,
    C_MINIVAN,
    C_MINIBUS,
    M_STANDARD,
    M_CRUISER,
    M_CHOPPER,
    M_TOURING,
    M_MOTOCROSS,
    M_SPORT,
    M_SUPER,
    M_TRAIL,
    M_SCOOTER,
    M_OFFROAD,
    M_UNDERBONE,
    M_TRICYCLE,
    M_AT
}
